name: Code Server

on:
  push:
    paths:
      - 'code-server/**'
  schedule:
    - cron: '0 0 1,15 * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build the image
        run: (cd code-server; docker build .)
