name: Gulp

on:
  push:
    branches: [ master ]
    paths:
      - 'gulp/**'
      - '.github/workflows/gulp.yaml'
  pull_request:
    paths:
      - 'gulp/**'
      - '.github/workflows/gulp.yaml'
  schedule:
    - cron: '0 0 1,15 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [8]

    steps:
      - uses: actions/checkout@v2

      - name: Build the image
        run: |
          cd gulp/node/${{ matrix.node }}
          docker build . --tag monsieurbiz/gulp:node-${{ matrix.node }}

      - name: Push the image
        if: (github.event_name == 'push' || github.event_name == 'schedule') && github.ref == 'refs/heads/master'
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push monsieurbiz/gulp:node-${{ matrix.node }}
