name: Gulp

on:
  push:
    paths:
      - 'gulp/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [8]

    steps:
      - uses: actions/checkout@v2

      - name: Build the image
        run: (cd gulp/node/${{ matrix.node }}; docker build .)
