name: Gulp

on:
  push:
    paths:
      - 'gulp/**'
      - '.github/workflows/gulp.yaml'
  pull_request:
    paths:
      - 'gulp/**'
      - '.github/workflows/gulp.yaml'
  schedule:
    - cron: '0 0 1,15 * *'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [8]

    steps:
      - uses: actions/checkout@v2

      - name: Build the image
        run: (cd gulp/node/${{ matrix.node }}; docker build .)
