name: HTTPd

on:
  push:
    paths:
      - 'httpd/**'
  schedule:
    - cron: '0 0 1,15 * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build the image
        run: (cd httpd/; docker build .)
