name: Jekyll

on:
  push:
    branches: [ master ]
    paths:
      - 'jekyll/**'
      - '.github/workflows/jekyll.yaml'
  pull_request:
    paths:
      - 'jekyll/**'
      - '.github/workflows/jekyll.yaml'
  schedule:
    - cron: '0 0 1,15 * *'
  workflow_dispatch:

jobs:
  build:
    name: latest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build the image
        run: |
          cd jekyll
          docker build . --tag monsieurbiz/jekyll:latest
          docker images

      - name: Push the image
        if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/master'
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push monsieurbiz/jekyll:latest
