name: MariaDB

on:
  push:
    paths:
      - 'mariadb/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        tag: [10.1, 10.2, latest]

    steps:
      - uses: actions/checkout@v2

      - name: Build the image
        run: (cd mariadb/${{ matrix.tag }}/; docker build .)
