name: PHP

on:
  push:
    paths:
      - 'php/**'
  schedule:
    - cron: '0 0 1,15 * *'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [5, 7.0, 7.1, 7.2, 7.3, 7.4, 7]
        type: [apache, cli, fpm]

    steps:
      - uses: actions/checkout@v2

      - name: Build the image
        run: (cd php/${{ matrix.php }}/${{ matrix.type }}/; docker build .)
