name: Rsync

on:
  push:
    paths:
      - 'rsync/**'
      - '.github/workflows/rsync.yaml'
  schedule:
    - cron: '0 0 1,15 * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build the image
        run: (cd rsync/; docker build .)
